create Index component
htmlacademy-vue/918345-pizza-1 pull request #1
Opened 2022-05-08 05:42 UTC by Davydok

2022-05-08 08:42 UTC, enotke requested changes

2022-05-08 08:42 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                    <img class="dough__image" :src="dough.image" alt="" />
Не нужно менять верстку в макете. У класса dough__image есть модификаторы для каждого типа теста

2022-05-08 08:42 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                    <img class="dough__image" :src="dough.image" alt="" />
dough__input--light например

2022-05-08 08:42 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                  class="diameter__input diameter__input--small"
аналогично diameter__input--small, diameter__input--normal, diameter__input--large

2022-05-08 08:42 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                      <span class="filling">
filling--ham, filling--cheddar...

2022-05-08 08:42 UTC, enotke commented on src/frontend/src/views/Index.vue
> +.dough__image {
Если использовать готовую верстку, то эти стили будут лишними. Вообще идея в том, чтобы разделить один большой макет на компоненты и реализовать их взаимодействие между собой.

2022-05-11 14:55 UTC, Davydok commented on src/frontend/src/views/Index.vue
> +                  class="diameter__input diameter__input--small"
В данных pizza.json нет поля, которое можно подставить в модификатор.

2022-05-11 14:55 UTC, Davydok commented on src/frontend/src/views/Index.vue
> +                      <span class="filling">
В данных pizza.json нет поля, которое можно подставить в модификатор.

2022-05-11 14:55 UTC, Davydok commented on src/frontend/src/views/Index.vue
> +.dough__image {
В данных pizza.json нет поля, которое можно подставить в модификатор.

2022-05-11 14:56 UTC, Davydok commented on src/frontend/src/views/Index.vue
> +                    <img class="dough__image" :src="dough.image" alt="" />
В данных pizza.json нет поля, которое можно подставить в модификатор.

2022-05-11 22:54 UTC, enotke commented on src/frontend/src/views/Index.vue
> +.dough__image {
Да, есть такое. По хорошему бекенд должен отдавать какой-нибудь slug. Но всё же городить свою верстку не вариант.
Можно использовать какие-нибудь мапперы и вычислять slug из поля image или использовать соответствия `{'Тонкое' => 'light'}`

2022-05-14 09:17 UTC, merged